apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../apps/envs/qa

components:
  - ../../../../../components/envs/qa

generators:
  - ./helm

patches:
  - path: root.yaml
