---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: powerdns
spec:
  values:
    controllers:
      main:
        containers:
          bootstrap-zone:
            env:
              ZONE: poc.iseja.net
          main:
            env:
              ZONE: poc.iseja.net
