apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-param
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  CLUSTER_ENVIRONMENT: src
  CLUSTER_NAME: src-vehagn-tg
  DOMAIN_BASE: src.iseja
  DOMAIN_TLD: net
