- source:
    kind: ConfigMap
    name: cluster-param
    fieldPath: data.DOMAIN_TLD
  targets:
    - fieldPaths:
        - spec.rules.0.host
      options:
        delimiter: "."
        index: 2
      select:
        kind: Ingress
- source:
    kind: ConfigMap
    name: cluster-param
    fieldPath: data.DOMAIN_BASE
  targets:
    - fieldPaths:
        - spec.rules.0.host
      options:
        delimiter: "."
        index: 1
      select:
        kind: Ingress
