- source:
    kind: ConfigMap
    name: cluster-param
    fieldPath: data.DOMAIN_TLD
  targets:
    - fieldPaths:
        - spec.hostnames.*
      options:
        delimiter: "."
        index: 2
      select:
        kind: TLSRoute
- source:
    kind: ConfigMap
    name: cluster-param
    fieldPath: data.DOMAIN_BASE
  targets:
    - fieldPaths:
        - spec.hostnames.*
      options:
        delimiter: "."
        index: 1
      select:
        kind: TLSRoute
