---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  template:
    spec:
      containers:
        - name: mongodb
          # track version in this environment explicitly
          image: docker.io/mongo:8.0.20@sha256:d8475449c75511307c8fc604bda3ef009cf764b8f2ae27b9d19cc26097efed96
