apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../../../../_components/qa

patches:
  - path: deployment-frontend.yaml
  - path: svc-frontend.yaml