---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - ../../../../../../apps/diag/whoami/base/flux
  # - ../../../../../../apps/dns/adguard/base/flux
  # - ../../../../../../apps/dns/unbound/base/flux
  - ../../../../../../apps/monitoring/metrics-server/base/flux
  
