---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: unifi
      labels:
        app: mongodb
    spec:
      containers:
        - env:
            - name: PUID
              value: "999"
            - name: PGID
              value: "999"
            - name: TZ
              value: Europe/Berlin
            - name: MONGO_AUTHSOURCE
              value: admin
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: root_user
                  name: db-secret-sealed
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: root_pass
                  name: db-secret-sealed
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  key: mongo_user
                  name: db-secret-sealed
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  key: mongo_pass
                  name: db-secret-sealed
            - name: MONGO_DBNAME
              value: unifidb
          image: docker.io/mongo:8.0.30@sha256:4a0f30875898413139bec44c73c02a05fed172578de65b644dcdcee143ae7306
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   readOnlyRootFilesystem: false
          #   capabilities:
          #     drop: [ "ALL" ]
          name: mongodb
          ports:
            - containerPort: 27017
              name: mongodb
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 350Mi
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/init-mongo.sh
              name: mongodb-init
              readOnly: true
              subPath: init-mongo.sh
            - mountPath: /data/db
              name: mongodb-data
      nodeSelector:
        topology.kubernetes.io/zone: pve4
      securityContext:
        runAsNonRoot: false
        # runAsNonRoot: true
        # runAsUser: 999
        # runAsGroup: 999
        # fsGroup: 999
        # fsGroupChangePolicy: OnRootMismatch
        # seccompProfile:
        #   type: RuntimeDefault
      volumes:
        - configMap:
            name: mongodb-init
          name: mongodb-init
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-data
