---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  labels:
    app: unifi-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-controller
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: unifi
      labels:
        app: unifi-controller
    spec:
      containers:
        - env:
            - name: PUID
              value: "999"
            - name: PGID
              value: "999"
            - name: TZ
              value: Europe/Berlin
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  key: mongo_user
                  name: db-secret-sealed
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  key: mongo_pass
                  name: db-secret-sealed
            - name: MONGO_HOST
              value: mongodb
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DBNAME
              value: unifidb
            - name: MONGO_AUTHSOURCE
              value: admin
          image: lscr.io/linuxserver/unifi-network-application:10.6.101@sha256:ccadcad5c640c91388d79e66a3751e4de3c9accdcef181f76c142aeca612214d
          name: unifi-network-application
          ports:
            # required
            - containerPort: 8443
              name: web-admin
              protocol: TCP
            # required
            - containerPort: 6789
              name: speedtest
              protocol: TCP
            # required
            - containerPort: 8080
              name: device-comm
              protocol: TCP
            # optional
            - containerPort: 8880
              name: http-redirect
              protocol: TCP
            # optional
            - containerPort: 8843
              name: secure-redirect
              protocol: TCP
            # required
            - containerPort: 3478
              name: stun
              protocol: UDP
            # optional
            - containerPort: 5514
              name: snmp-trap
              protocol: UDP
            # required
            - containerPort: 10001
              name: unifi-disc
              protocol: UDP
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 50m
              memory: 500Mi
          volumeMounts:
            - mountPath: /config
              name: unifi-controller-data
      nodeSelector:
        topology.kubernetes.io/zone: pve4
      securityContext:
        runAsNonRoot: false
        # runAsNonRoot: true
        # runAsUser: 999
        # runAsGroup: 999
        # fsGroup: 999
        # fsGroupChangePolicy: OnRootMismatch
        # seccompProfile:
        #   type: RuntimeDefault
      volumes:
        - name: unifi-controller-data
          persistentVolumeClaim:
            claimName: unifi-controller-data
#    volumes:
#      - /srv/docker-compose/hosts/unifi/data:/config
