apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: unifi

components:
  - ../../../../components/apps/storage/pvc

resources:
  - ns.yaml
  - pvc-frontend.yaml
  - deployment-frontend.yaml
  - svc-frontend.yaml
