apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  # - svc.yaml
  - deployment.yaml
  - pvc.yaml

configMapGenerator:
  - name: mongodb-init
    namespace: unifi
    files:
      - assets/init-mongo.js