apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-controller-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M
  storageClassName: proxmox-csi
  volumeName: pv-unifi
