apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-controller-data
  namespace: unifi
spec:
  storageClassName: proxmox-csi
  volumeName: pv-unifi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
