apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test
# namePrefix: poc-

resources:
- ../../base

# components:
# - ../variants/non-prod
# - ../variants/home

patches:
- path: talconfig.env.yaml
# - path: talconfig.patches.yaml
#   target:
#     kind: generic-yaml
#     name: talconfig
