kind: generic-yaml
metadata:
  name: talconfig

endpoint: https://test-talos-cp-01.${domainName}:6443

nodes:
  - hostname: test-talos-cp-01.${domainName}
    ipAddress: ${controlPlaneIP_1}
    controlPlane: true
    installDisk: /dev/sda
  - hostname: test-talos-worker-01.${domainName}
    ipAddress: ${workerIP_1}
    controlPlane: false
    installDisk: /dev/sda
  - hostname: test-talos-worker-02.${domainName}
    ipAddress: ${workerIP_2}
    controlPlane: false
    installDisk: /dev/sda

