apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replacements:
  - path: repl/gateway-replace-hostname.yaml
  - path: repl/ingress-replace-domain.yaml
  - path: repl/httproute-replace-domain.yaml
  - path: repl/tlsroute-replace-domain.yaml
