---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}
spec:
  accessModes:
    - ${STORAGE_ACCESSMODES:=ReadWriteOnce}
  dataSourceRef:
    kind: Restore
    name: ${APP}
    apiGroup: kopiur.home-operations.com
  resources:
    requests:
      storage: ${STORAGE_CAPACITY:=5Gi}
  storageClassName: ${STORAGE_CLASS:=longhorn-standard}
