apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-param
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  CLUSTER_ENVIRONMENT: rebuild
  DOMAIN_BASE: rebuild.iseja
  DOMAIN_TLD: net
