apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# components:
#   - ../../../../../_components/dev

resources:
  - ../../base
  - http-route.yaml

helmCharts:
  - name: checkmk
    repo: https://checkmk.github.io/checkmk_kube_agent
    version: 1.6.0
    releaseName: checkmk-kube-agent
    namespace: checkmk-agent
    # no values.yaml as defaults are good (ingress disabled in favor of GW API http-route)
    # valuesFile: values.yaml