clusterCollector:
  ingress:
    enabled: false
    annotations:
      io.cilium/lb-ipam-ips: 10.8.3.89
    hosts:
      - host: checkmk-cluster-collector.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local