apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Manually render ServiceMonitors since Argo CD chart checks if they exist
# Argo CD thinks the cluster doesn't have this capability
# Could possibly alter the plugin
# > helm template argo/argo-cd --api-versions monitoring.coreos.com/v1 -f values.yaml

resources:
  - ns.yaml
  - http-route.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 8.2.5
    releaseName: "argocd"
    namespace: argocd
    valuesFile: values.yaml
