apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: unifi

components:
  - ../../../../components/apps/storage/pvc

resources:
  - ns.yaml
  - pvc-db.yaml
  - db-secret.unencrypted.yaml.example
  - deployment.yaml
  - svc.yaml
  - db-secret.sealed.yaml

configMapGenerator:
  - name: mongodb-init
    files:
      - assets/init-mongo.sh
