---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name checkmk-kube-agent
spec:
  chart:
    spec:
      chart: checkmk
      sourceRef:
        kind: HelmRepository
        name: *name
        namespace: *name
      version: 1.12.1
  interval: 1h
  timeout: 10m
  values:
    clusterCollector:
      resources:
        limits:
          cpu: 100m
          memory: 120Mi
        requests:
          cpu: 30m
          memory: 70Mi
    nodeCollector:
      cadvisor:
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 15m
            memory: 40Mi
      containerMetricsCollector:
        resources:
          limits:
            cpu: 100m
            memory: 50Mi

          requests:
            cpu: 15m
            memory: 40Mi
      machineSectionsCollector:
        resources:
          limits:
            cpu: 100m
            memory: 40Mi
          requests:
            cpu: 30m
            memory: 35Mi
      # collect metrics also on control plane nodes
      tolerations:
        - effect: "NoSchedule"
          operator: "Exists"
