- source:
    kind: ConfigMap
    name: cluster-param
    fieldPath: data.CLUSTER_ENVIRONMENT
  targets:
    - select:
        kind: HTTPRoute
      fieldPaths:
        - spec.hostnames.*
      options:
        delimiter: "-"
        index: -1
