- source:
    kind: ConfigMap
    name: cluster-param
    fieldPath: data.CLUSTER_ENVIRONMENT
  targets:
    - select:
        kind: Ingress
      fieldPaths:
        - spec.rules.*.host
      options:
        delimiter: "-"
        index: -1