- source:
    kind: ConfigMap
    name: cluster-param
    fieldPath: data.CLUSTER_ENVIRONMENT
  targets:
    - fieldPaths:
        - spec.hostnames.*
      options:
        delimiter: "-"
        index: -1
      select:
        kind: TLSRoute
