version: '3'
services:
  borgmatic:
    image: b3vis/borgmatic@sha256:d9f51fdf6d7c32e4bad1d13a5282aac33df6f7c8f22769e50b6438c8f9963390
    container_name: borgmatic
    volumes:
      - ${VOLUME_SOURCE}:/mnt/source:ro           # backup source
      - ${VOLUME_TARGET}:/mnt/borg-repository     # backup target
      - ${VOLUME_ETC_BORGMATIC}:/etc/borgmatic.d/ # borgmatic config file(s) + crontab.txt
      - ${VOLUME_BORG_CONFIG}:/root/.config/borg  # config and keyfiles
      - ${VOLUME_SSH}:/root/.ssh                  # ssh key for remote repositories
      - ${VOLUME_BORG_CACHE}:/root/.cache/borg    # checksums used for deduplication
    environment:
      - TZ=${TZ}
      - BORG_PASSPHRASE=${BORG_PASSPHRASE}
