---
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  # authSecretRef: bgp-auth-secret
  ebgpMultihop: 4
  families:
    - advertisements:
        matchLabels:
          advertise: "bgp"
      afi: ipv4
      safi: unicast
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
