- source:
    kind: ConfigMap
    name: cluster-param
    fieldPath: data.DOMAIN_TLD
  targets:
    - select:
        kind: HTTPRoute
      fieldPaths:
        - spec.hostnames.*
      options:
        delimiter: "."
        index: 2
- source:
    kind: ConfigMap
    name: cluster-param
    fieldPath: data.DOMAIN_BASE
  targets:
    - select:
        kind: HTTPRoute
      fieldPaths:
        - spec.hostnames.*
      options:
        delimiter: "."
        index: 1
