---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: powerdns-tsig-dynupdate
spec:
  dataFrom:
    - extract:
        key: powerdns-tsig-dynupdate#base
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: powerdns-tsig-dynupdate
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: powerdns-tsig-axfr-out
spec:
  dataFrom:
    - extract:
        key: powerdns-tsig-axfr-out#base
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: powerdns-tsig-axfr-out
