---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: snapshot-controller
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.1.0
    digest: sha256:8bdb99b574cbc791a07996ab7333a5e8c2915e794c992b4057aa45f3f48922bd
  url: oci://ghcr.io/home-operations/charts/snapshot-controller
