---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
spec:
  provider:
    onepassword:
      auth:
        secretRef:
          connectTokenSecretRef:
            key: OP_CONNECT_TOKEN
            name: onepassword-connect-vault-secret
            namespace: external-secrets
      connectHost: http://onepassword-connect.external-secrets.svc.cluster.local
      vaults:
        K8S: 1
