---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: onepassword-connect
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    digest: sha256:c0e87d231e5b082ad39bda4f3f0890a9923fe5d70694cadc4f7b4cc0f9df6c0c
    tag: 2.4.2
  url: oci://ghcr.io/1password/connect
