apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../base # configures domain replacement
  - ../../transformers/prefix-domain
  - ../../transformers/kopiur-secret-env

resources:
  - cluster-param.yaml
