apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: unbound

configMapGenerator:
  - name: unbound-conf
    namespace: unbound
    files:
      - config/conf.d/logging-default.conf

resources:
  - ns.yaml
  - deployment.yaml
  - svc.yaml
