apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../components/envs/dbg

resources:
  - ../../base
  - ../../apps/envs/dbg

generators:
  - ./helm

patches:
  - path: root.yaml
