---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  chartRef:
    kind: OCIRepository
    name: sealed-secrets
  interval: 1h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    namespace: sealed-secrets
    keyrenewperiod: 8766h # ~ 1 year

    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi

