---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: sealed-secrets
spec:
  interval: 1h
  ref:
    tag: 2.19.3
    digest: sha256:0a22f95d56c30e5e9778bf887ba7e3e68b6570356c3d9de4921f3816edf098f5
  url: oci://registry-1.docker.io/bitnamicharts/sealed-secrets
