---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: sealed-secrets
spec:
  interval: 1h
  ref:
    tag: 2.19.2
    digest: sha256:0722ab2239e9e754599c956d0a6050e7a3636ea9c5c5c8c087e9149ec5223263
  url: oci://registry-1.docker.io/bitnamicharts/sealed-secrets
