---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: sealed-secrets
spec:
  interval: 1h
  ref:
    digest: sha256:9e60fff9c99e22028d5b2cdc223bc669709cdd7447b9aef76714146a40932eec
    tag: 2.20.0
  url: oci://registry-1.docker.io/bitnamicharts/sealed-secrets
