apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../base # configures domain replacements already
  # do not prefix domain
  # - ../../transformers/prefix-domain   # prefix domain
  - ../../transformers/kopiur-secret-env

resources:
  - cluster-param.yaml
