apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: adguard
    spec:
      containers:
        - image: docker.io/adguard/adguardhome:v0.107.79@sha256:aba9e3bf0613be3ba3755e1fc311b126e2c24bec25e18b6483894a88283074f0
          name: adguard
          ports:
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 67
              name: dhcp
              protocol: UDP
            - containerPort: 3000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          # capabilities:
          #   drop: [ "ALL" ]
          volumeMounts:
            - mountPath: /opt/adguardhome/conf
              name: config-folder
            - mountPath: /opt/adguardhome/work
              name: work-folder
      initContainers:
        - command: ["cp", "/tmp/AdGuardHome.yaml", "/opt/adguardhome/conf/AdGuardHome.yaml"]
          image: busybox@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
          name: copy-base-config
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp/AdGuardHome.yaml
              name: config
              subPath: AdGuardHome.yaml
            - mountPath: /opt/adguardhome/conf
              name: config-folder
        - command: ["sh", "-c", "cat /tmp/users.yaml >> /opt/adguardhome/conf/AdGuardHome.yaml"]
          image: busybox@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
          name: append-users
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp/users.yaml
              name: users
              subPath: users.yaml
            - mountPath: /opt/adguardhome/conf
              name: config-folder
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - configMap:
            name: adguard-config
          name: config
        - name: users
          secret:
            secretName: users
        - emptyDir: {}
          name: config-folder
        - emptyDir: {}
          name: work-folder
