apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adguard

configMapGenerator:
  - name: adguard-config
    files:
      - config/AdGuardHome.yaml

resources:
  - ns.yaml
  - svc.yaml
  - secret-users.yaml
  - deployment.yaml
  - http-route.yaml
