apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: adguard-config
    namespace: dns
    files:
      - config/AdGuardHome.yaml

resources:
  - svc.yaml
  - secret-users.yaml
  - deployment.yaml
  - http-route.yaml
