---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: users
  namespace: adguard
spec:
  encryptedData:
    users.yaml: AgBv0ieIFgypGWZyI/FTZRctzjB8o37hTt0v+Sn8hbuzWjCDylOHl3fHTw6kWHfBpALMIwxc1aiOWpbTbFIgMvu+oEtbrCvB4tWjjBNIZllnoRTXInJDq91HeZkjKSrUOvNu18M25ZJTvBCStxWPWMafnAepKTFz4lleP8Bs/OxLxB35B5XawXvH6igBfRp6I5/pddkVCtc3gUfijHTr+To1HpLO79OFKKa1WNKH4qefvMOQR5n2qVkXE7VhQp9j/XbFREeJ1MjceD9zDi5X2FFO7yhJPvV41oHBtyph80mt83DChro52yY3VBAK1wiT5razHLH8PY1wuNms4b5QZcPC3tHdHknTx7l2oXzeUAWbrcQRruoYcLWAkbDKfM/SnmGgD3lixRz3yaz/tbQr6AiegA4eLPjV52gIHLYReJOgoeVAb6fwCSorMV6TnyjLGDQ4nU+UUQIy8vj68ZDP/VWvNug/T71EZgfmYGwFD4H0hlpC2raDM9r+j6I8KC/K4JorRZCkfydSCoaQyzGDzsA2NlYtwPuAzinnE5GEhIOowv9M8kMsa8vdWgs/A9XfiM5KEksGwb0W8caZ5S1lFnHLQD29xkwq1AY9FIm8vLdppOmj0XxMYY7v/TgXcK5Rmezv01FUx1SgeeQoqIfenunLbrTPrabqnjKgEFbuu65xii4yshLDKrkmdQE7ZXZJVnBEGOMZlrKEEtvh3vwO1aTdSJ2Qyqy8q+XZT56yyIyWMypP3+hLQS53T01a5z1kbmDFraR84kpq7fcTbf0H+5ByEfwu0ph1+muah7UZcKumX0WAtRheejAmCNXoAZkdiCScsspzVRBL
  template:
    metadata:
      name: users
      namespace: adguard
