---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: users
  namespace: dns
spec:
  encryptedData:
    users.yaml: AgA6uvXrycI0pm22z/5R/PqPrnd++bw2RwdTjzf+8lKUgra5YJQ4Bh6BbPlglYbkhUCMN96Pg8wktG3Sujhg5sysrlsOXge4UyO6tl0fQ1vMaODLuzeJrawKnm2WXqZ6tTocxA3/BlHhL5Mo3M1rplgE5zOZVhe9rYhEUTd2V6QjvE7hLxf11BEZFqDr3EFiuWd+zLY2zL0+XuOC2Ur/G/ncLY3jEJEisxJRmsgkm/YX5RPr+V9ppwqSyAJedf0ME2PCQM3yZb1XjYMk8RDlhnaP/cQV/l/QCoU/OocpNaCVh1lOgETDm5oAEMqKTBir9UWCQ/bNFzPB0rIU80PFKtTe28fK0vD/OatVqvqORe8nD+ZNRv8b6nIwS/JKQGFI3SDuyX5UiysSWvAPvJ+FJ/jm/WyoPSS84y853FIAuR0/8j/QVSpv0u/lQJ3oUm9a/0eFH+5ErpdH+IQFfEQu+xrk/2/yZyUHcu58i1uI5M/cEb2t1WEgHawDKXsDlcb1uNbce6A/sH/ug7rjRPJsCSp+rYwCEqe5gv5TAuYD9/QTpjsyHHA8vupPPxikkEqiKNPoLeoRkeONL5V/m48sUmK1qRBnXaN3xndWdMuG6zbj7E3PkjziVMZJGpL/QJF7weo3NSYyG4RG+QqrEWoNYm4G0XzpPqtm3h2buKC9hveMDY1qRSixAhNSbGcOWsKTbX+R8m2Ny/aJuyJmfr6OKhs6WaB7C9QaGBA/kPunZufPzcMEQQC55JMXpFKDzYGYUpj9O1rq1C0qhPaKXjIdikmN6FjHTfStI/dAATrMnP/P6eZ07LtBX0pSPmcwF/As/9Rh7H82hfZmObxpx8cIJDxNIbYBJMDZV0Z1xs2x+vzIU3hgQdZGLU5Pqd2/GydNoVblRz/MdmDs1wM7be6acIMzANWYvXpc5mSsfS2X6aSaLaxsiFfK3VzdH+9fKhHn/mc1FaMaS6lQ80jfsUAzHB/S4G6ywRGfIJvIRSSAfg71QNXbb8bA9sp64B7LikEn5cCOywoApCuVrgLXVs/vNIaqFvNEe35+oZRUpY+3CQfy
  template:
    metadata:
      name: users
      namespace: dns
