apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: longhorn
valuesInline:
  defaultBackupStore:
    backupTarget: "s3://prod-longhorn-backup@local/default"
    backupTargetCredentialSecret: longhorn-minio-credentials
