# replace .spec.interval of all Flux Kustomizations with the value of FLUX_RECONCILIATION_INTERVAL from the cluster-param ConfigMap 
- source:
    fieldPath: data.FLUX_RECONCILIATION_INTERVAL
    kind: ConfigMap
    name: cluster-param
  targets:
    - fieldPaths:
        - spec.interval
      select:
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization