---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-backup
  namespace: longhorn-system
spec:
  concurrency: 1
  # daily at 4:30 AM
  cron: "30 4 * * *"
  # Applies to volumes without explicit group
  groups:
    - default
  retain: 7
  task: backup
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: weekly-backup
  namespace: longhorn-system
spec:
  concurrency: 1
  # weekly at 4:04 AM
  cron: "4 4 * * 0"
  # Applies to volumes without explicit group
  groups:
    - default
  retain: 4
  task: backup
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: monthly-backup
  namespace: longhorn-system
spec:
  concurrency: 1
  # monthly at 4:12 AM on the 1st
  cron: "12 4 1 * *"
  # Applies to volumes without explicit group
  groups:
    - default
  retain: 6
  task: backup
