# Hourly snapshots for all (default) volumes
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: hourly-snapshot
  namespace: longhorn-system
spec:
  concurrency: 3
  cron: "0 * * * *"
  groups:
    - default
  retain: 24
  task: snapshot
