apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-param
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  CLUSTER_ENVIRONMENT: head
  DOMAIN_BASE: head.iseja
  DOMAIN_TLD: net
