apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
spec:
  dnsNames:
    # rewrite by kustomize set up for wildcard domain only
    - "*.example.com"
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
    group: cert-manager.io
  secretName: cert
  usages:
    - digital signature
    - key encipherment
