apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: whoami
  # labels:
    # app: whoami
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: whoami
          image: ghcr.io/traefik/whoami:v1.10
