apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
#   - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

helmCharts:
  - name: metrics-server
    repo: https://kubernetes-sigs.github.io/metrics-server/
    version: 3.13.0
    releaseName: metrics-server
    namespace: kube-system