apiVersion: v1
kind: Service
metadata:
  name: whoami
  annotations:
    io.cilium/lb-ipam-ips: 192.168.8.87
spec:
  externalTrafficPolicy: Local
  ports:
    - name: web
      port: 80
      targetPort: http
  selector:
    app: whoami
  type: LoadBalancer
