apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org./directory
    email: qa-certmanager@iseja.net