apiVersion: builtin
kind: LabelTransformer
metadata:
  name: label-ConfigMaps
fieldSpecs:
- kind: ConfigMap
  create: true
  path: metadata/labels
labels:
  # Forces Flux to immediately upgrade the HelmRelease when this ConfigMap changes
  reconcile.fluxcd.io/watch: "Enabled"