apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# needed by configMapGenerator
namespace: adguard

components:
  - ../../../../../components/envs/qa

resources:
  - ../../base

configMapGenerator:
  - files:
      - config/AdGuardHome.yaml
    name: adguard-config-local
patches:
  - path: svc.yaml
  - path: merge-deployment.yaml

