apiVersion: apps/v1
kind: Deployment
metadata:
  name: kopiur-test
  labels:
    app: kopiur-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kopiur-test
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: kopiur-test
      labels:
        app: kopiur-test
    spec:
      containers:
        - name: kopiur-test
          args:
            - |
              echo "hello from $(hostname) at $(date -Iseconds)" >> /data/marker.txt
              cat /data/marker.txt
              sleep infinity
          command: ["/bin/sh", "-c"]
          image: docker.io/library/busybox:1.37@sha256:9db7b59979c38555a39def84a31fb98b5296952f9e3afd4f6f11f05b07adfab0
          resources:
            limits:
              cpu: 100m
              memory: 32Mi
            requests:
              cpu: 10m
              memory: 16Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: data
              mountPath: /data
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kopiur-test
