apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

labels:
  - pairs:
      env: prod
    includeSelectors: true  # This ensures Deployment selectors are updated
    includeTemplates: true  # This ensures Pod templates get the labels
resources:
  - cluster-param.yaml

components:
  - ../base # configures domain replacements already
  # do not prefix domain
  # - ../../_transformers/prefix-domain   # prefix domain
