apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-cluster-issuer
spec:
  acme:
    email: certmanager@example.com
    privateKeySecretRef:
      name: cloudflare-key
    # server: https://acme-v02.api.letsencrypt.org./directory
    server: https://acme-staging-v02.api.letsencrypt.org./directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              key: api-token
              name: cloudflare-api-token
