apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../cert-manager/cert-manager-core/envs/qa
  - ../../cert-manager/cert-manager/envs/qa
  - ../../kube-system/kubelet-serving-cert-approver/envs/qa
  - ../../gateway-api/gateway/envs/qa
  - ../../gateway-api/gateway-redirect/envs/qa
  - ../../csi-proxmox/proxmox-csi/envs/qa
