---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  namespace: unifi
  labels:
    app: unifi-controller
spec:
  template:
    spec:
      containers:
        - name: unifi-network-application
          image: lscr.io/linuxserver/unifi-network-application:8.6.9@sha256:882e7c6e811a8c3cdd5f77ce752fc109a4f085217eedb695fdd717a42ada65fd
          env:
            - name: MONGO_HOST
              value: dev-mongodb
