---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  namespace: unifi
  labels:
    app: unifi-controller
spec:
  template:
    spec:
      containers:
        - name: unifi-network-application
          image: lscr.io/linuxserver/unifi-network-application:9.0.114@sha256:1fb43625e37e6d618f1c0d9cbea2fa3fa05a608a7c5379078773a72fe1bbb839
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret-sealed
                  key: mongo_user
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret-sealed
                  key: mongo_pass        