---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  namespace: unifi
  labels:
    app: unifi-controller
spec:
  template:
    spec:
      containers:
        - name: unifi-network-application
          # track version in this environment explicitly
          image: lscr.io/linuxserver/unifi-network-application:9.3.45

