---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  namespace: unifi
  labels:
    app: unifi-controller
spec:
  template:
    spec:
      containers:
        - name: unifi-network-application
          # track version in this environment explicitly
          image: lscr.io/linuxserver/unifi-network-application:9.5.21@sha256:27ab5832669e95ca09f477b915efc7efbd2404458251570fc20330792b56f5a9

