---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  namespace: unifi
  labels:
    app: unifi-controller
spec:
  template:
    spec:
      containers:
        - name: unifi-network-application
          image: lscr.io/linuxserver/unifi-network-application:9.3.45@sha256:022dc69b44c28f39d6beb4a269a02f4d0794ec4513d0625eaa2357f4974fdd7f
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret-sealed
                  key: mongo_user
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret-sealed
                  key: mongo_pass        