---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  namespace: unifi
  labels:
    app: unifi-controller
spec:
  template:
    spec:
      containers:
        - name: unifi-network-application
          # track version in this environment explicitly
          image: lscr.io/linuxserver/unifi-network-application:10.0.160@sha256:f782557d505f16a9dac8fac7bfdfc865c272ce497e6fd0b66ef0822a0893f08d

