apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../_components/dev

resources:
  - ../../base
  - db-secret.sealed.yaml

patches:
  - path: deployment-db.yaml
  - path: deployment-frontend.yaml
  - path: svc-frontend.yaml