apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      env: qa               # This label is added to (almost) all resources
    includeSelectors: true  # This ensures Deployment selectors are updated
    includeTemplates: true  # This ensures Pod templates get the labels

resources:
  - ../../base

components:
  - ../../../../../_components/qa

patches:
  - path: svc.yaml
  - path: deployment.yaml