apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-param
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  CLUSTER_ENVIRONMENT: qa
  CLUSTER_NAME: qa-vehagn-tg
  DOMAIN_BASE: qa.iseja
  DOMAIN_TLD: net
