apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namePrefix: qa-

resources:
  - cluster-param.yaml

components:
  - ../base   # configures domain replacement
  - ../../_transformers/prefix-domain
  - ../../_transformers/replace-domain