name: "Actionlint"
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  actionlint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - run: scripts/install-actionlint.sh "$HOME/.local/bin"
    - run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"
    - run: actionlint -color
