name: "Kustomize build"
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  kustomize-build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: azure/setup-kubectl@829323503d1be3d00ca8346e5391ca0b07a9ab0d # v5.1.0
    - run: scripts/install-kubeconform.sh "$HOME/.local/bin"
    - run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"
    - run: scripts/kustomize-build-all.sh
